using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using WarThunderComparer.comparerData.Adapters;
using WarThunderComparer.comparerData.Collections;
using Android.Media;

namespace WarThunderComparer.comparerData.Collections
{
    class HeliCollection
    {
        public static List<Heli> GetHeli()
        {
            Context context = Application.Context;

            List<Heli> helis = new List<Heli>();
            Heli heli;
            helis.Clear();

            ///////////////////////////////////////////   США   ///////////////////////////////////////////

            heli = new Heli();
            heli.Id = 31501;
            heli.Image = Resource.Drawable.img31501;
            heli.FlagImage = Resource.Drawable._flagUSA;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestUS;
            heli.Name ="AH-1G";
            heli.Nation =context.Resources.GetString(Resource.String.NationUSA);
            heli.NationId = 1;
            heli.Rank = "V";
            heli.RankId = 5;
            heli.BR = 8.0;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.81;
            heli.FirstFlyYear = 1965;
            heli.MaxSpeed = 317;
            heli.ClimbTo1000 = 79;
            heli.Turn360 = 7;
            heli.EnginePower = 1100;
            heli.Weight = 4300;
            heli.ThrustToWeightRatio = 0.26;
            heli.AGMCount = 0;
            heli.AGMArmorPenetration = 0;
            heli.AGMSpeed = 0;
            heli.AGMRange = 0;
            heli.ASMCount = 76;
            heli.ASMArmorPenetration = 290;
            heli.ASMSpeed = 739;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon31501);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon31501);
            heli.HandingAGM = false;
            heli.HandingASM= true;
            heli.HandingCannon = true;
            heli.HandingBomb = false;
            helis.Add(heli);

            heli = new Heli();
            heli.Id = 31502;
            heli.Image = Resource.Drawable.img31502;
            heli.FlagImage = Resource.Drawable._flagUSA;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestUS;
            heli.Name = "UH-1B";
            heli.Nation = context.Resources.GetString(Resource.String.NationUSA);
            heli.NationId = 1;
            heli.Rank = "V";
            heli.RankId = 5;
            heli.BR = 8.7;
            heli.Type = context.Resources.GetString(Resource.String.UtilityHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.81;
            heli.FirstFlyYear = 1956;
            heli.MaxSpeed = 258;
            heli.ClimbTo1000 = 71;
            heli.Turn360 = 7;
            heli.EnginePower = 1100;
            heli.Weight = 3900;
            heli.ThrustToWeightRatio = 0.28;
            heli.AGMCount = 6;
            heli.AGMArmorPenetration = 500;
            heli.AGMSpeed = 190;
            heli.AGMRange = 3000;
            heli.ASMCount = 76;
            heli.ASMArmorPenetration = 290;
            heli.ASMSpeed = 739;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon31502);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon31502);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = false;
            helis.Add(heli);

            heli = new Heli();
            heli.Id = 31503;
            heli.Image = Resource.Drawable.img31503;
            heli.FlagImage = Resource.Drawable._flagUSA;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestUS;
            heli.Name = "UH-1C";
            heli.Nation = context.Resources.GetString(Resource.String.NationUSA);
            heli.NationId = 1;
            heli.Rank = "V";
            heli.RankId = 5;
            heli.BR = 9.3;
            heli.Type = context.Resources.GetString(Resource.String.UtilityHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.81;
            heli.FirstFlyYear = 1965;
            heli.MaxSpeed = 258;
            heli.ClimbTo1000 = 71;
            heli.Turn360 = 7;
            heli.EnginePower = 1100;
            heli.Weight = 4300;
            heli.ThrustToWeightRatio = 0.26;
            heli.AGMCount = 6;
            heli.AGMArmorPenetration = 630;
            heli.AGMSpeed = 296;
            heli.AGMRange = 3000;
            heli.ASMCount = 76;
            heli.ASMArmorPenetration = 290;
            heli.ASMSpeed = 739;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon31503);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon31503);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = false;
            helis.Add(heli);
            

            heli = new Heli();
            heli.Id = 31504;
            heli.Image = Resource.Drawable.img31504;
            heli.FlagImage = Resource.Drawable._flagUSA;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestUS;
            heli.Name = "◊ UH-1C XM-30";
            heli.Nation = context.Resources.GetString(Resource.String.NationUSA);
            heli.NationId = 1;
            heli.Rank = "V";
            heli.RankId = 5;
            heli.BR = 9.3;
            heli.Type = context.Resources.GetString(Resource.String.UtilityHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypePremium);
            heli.PatchAdded = 1.81;
            heli.FirstFlyYear = 1965;
            heli.MaxSpeed = 258;
            heli.ClimbTo1000 = 71;
            heli.Turn360 = 7;
            heli.EnginePower = 1100;
            heli.Weight = 3900;
            heli.ThrustToWeightRatio = 0.28;
            heli.AGMCount = 6;
            heli.AGMArmorPenetration = 630;
            heli.AGMSpeed = 296;
            heli.AGMRange = 3000;
            heli.ASMCount = 44;
            heli.ASMArmorPenetration = 290;
            heli.ASMSpeed = 739;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon31502);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon31504);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = false;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 31601;
            heli.Image = Resource.Drawable.img31601;
            heli.FlagImage = Resource.Drawable._flagUSA;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestUS;
            heli.Name = "AH-1F";
            heli.Nation = context.Resources.GetString(Resource.String.NationUSA);
            heli.NationId = 1;
            heli.Rank = "VI";
            heli.RankId = 6;
            heli.BR = 9.7;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.81;
            heli.FirstFlyYear = 1981;
            heli.MaxSpeed = 355;
            heli.ClimbTo1000 = 59;
            heli.Turn360 = 7;
            heli.EnginePower = 1300;
            heli.Weight = 4500;
            heli.ThrustToWeightRatio = 0.25;
            heli.AGMCount = 8;
            heli.AGMArmorPenetration = 630;
            heli.AGMSpeed = 296;
            heli.AGMRange = 3000;
            heli.ASMCount = 76;
            heli.ASMArmorPenetration = 290;
            heli.ASMSpeed = 739;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon31601);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon31601);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = false;
            heli.IRCM = true;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 31602;
            heli.Image = Resource.Drawable.img31602;
            heli.FlagImage = Resource.Drawable._flagUSA;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestUS;
            heli.Name = "AH-1Z";
            heli.Nation = context.Resources.GetString(Resource.String.NationUSA);
            heli.NationId = 1;
            heli.Rank = "VI";
            heli.RankId = 6;
            heli.BR = 10.0;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.81;
            heli.FirstFlyYear = 2000;
            heli.MaxSpeed = 355;
            heli.ClimbTo1000 = 59;
            heli.Turn360 = 7;
            heli.EnginePower = 3600;
            heli.Weight = 8600;
            heli.ThrustToWeightRatio = 0.42;
            heli.AGMCount = 16;
            heli.AGMArmorPenetration = 1100;
            heli.AGMSpeed = 475;
            heli.AGMRange = 8000;
            heli.ASMCount = 76;
            heli.ASMArmorPenetration = 290;
            heli.ASMSpeed = 739;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon31602);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon31602);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = false;
            heli.Flares = true;
            heli.AirToAir = true;
            helis.Add(heli);


            /////////////////////////////////////////// ГЕРМАНИЯ ///////////////////////////////////////

            heli = new Heli();
            heli.Id = 32501;
            heli.Image = Resource.Drawable.img32501;
            heli.FlagImage = Resource.Drawable._flagFRG;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestFRG;
            heli.Name = "SA.313B Alouette II";
            heli.Nation = context.Resources.GetString(Resource.String.NationGermany);
            heli.NationId = 2;
            heli.Rank = "V";
            heli.RankId = 5;
            heli.BR = 8.7;
            heli.Type = context.Resources.GetString(Resource.String.UtilityHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.83;
            heli.FirstFlyYear = 1952;
            heli.MaxSpeed = 208;
            heli.ClimbTo1000 = 98;
            heli.Turn360 = 7;
            heli.EnginePower = 380;
            heli.Weight = 1600;
            heli.ThrustToWeightRatio = 0.24;
            heli.AGMCount = 4;
            heli.AGMArmorPenetration = 600;
            heli.AGMSpeed = 190;
            heli.AGMRange = 3000;
            heli.ASMCount = 72;
            heli.ASMArmorPenetration = 10;
            heli.ASMSpeed = 500;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon32501);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon32501);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = false;
            heli.HandingBomb = false;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 32502;
            heli.Image = Resource.Drawable.img32502;
            heli.FlagImage = Resource.Drawable._flagFRG;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestFRG;
            heli.Name = "UH-1D";
            heli.Nation = context.Resources.GetString(Resource.String.NationGermany);
            heli.NationId = 2;
            heli.Rank = "V";
            heli.RankId = 5;
            heli.BR = 9.3;
            heli.Type = context.Resources.GetString(Resource.String.UtilityHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.83;
            heli.FirstFlyYear = 1961;
            heli.MaxSpeed = 282;
            heli.ClimbTo1000 = 67;
            heli.Turn360 = 8;
            heli.EnginePower = 1300;
            heli.Weight = 4300;
            heli.ThrustToWeightRatio = 0.32;
            heli.AGMCount = 6;
            heli.AGMArmorPenetration = 500;
            heli.AGMSpeed = 190;
            heli.AGMRange = 3000;
            heli.ASMCount = 38;
            heli.ASMArmorPenetration = 290;
            heli.ASMSpeed = 739;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon32502);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon32502);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = false;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 32503;
            heli.Image = Resource.Drawable.img32503;
            heli.FlagImage = Resource.Drawable._flagFRG;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestFRG;
            heli.Name = "◊ BO 105 CB-2";
            heli.Nation = context.Resources.GetString(Resource.String.NationGermany);
            heli.NationId = 2;
            heli.Rank = "V";
            heli.RankId = 5;
            heli.BR = 9.7;
            heli.Type = context.Resources.GetString(Resource.String.UtilityHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypePremium);
            heli.PatchAdded = 1.83;
            heli.FirstFlyYear = 1967;
            heli.MaxSpeed = 262;
            heli.ClimbTo1000 = 110;
            heli.Turn360 = 7;
            heli.EnginePower = 840;
            heli.Weight = 2500;
            heli.ThrustToWeightRatio = 0.33;
            heli.AGMCount = 8;
            heli.AGMArmorPenetration = 630;
            heli.AGMSpeed = 296;
            heli.AGMRange = 3000;
            heli.ASMCount = 0;
            heli.ASMArmorPenetration = 0;
            heli.ASMSpeed = 0;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon32503);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon32503);
            heli.HandingAGM = true;
            heli.HandingASM = false;
            heli.HandingCannon = false;
            heli.HandingBomb = false;
            heli.Flares = true;
            helis.Add(heli);

            heli = new Heli();
            heli.Id = 32601;
            heli.Image = Resource.Drawable.img32601;
            heli.FlagImage = Resource.Drawable._flagFRG;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestFRG;
            heli.Name = "BO 105 PAH-1";
            heli.Nation = context.Resources.GetString(Resource.String.NationGermany);
            heli.NationId = 2;
            heli.Rank = "VI";
            heli.RankId = 6;
            heli.BR = 9.7;
            heli.Type = context.Resources.GetString(Resource.String.UtilityHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.83;
            heli.FirstFlyYear = 1967;
            heli.MaxSpeed = 261;
            heli.ClimbTo1000 = 118;
            heli.Turn360 = 8;
            heli.EnginePower = 840;
            heli.Weight = 2500;
            heli.ThrustToWeightRatio = 0.33;
            heli.AGMCount = 6;
            heli.AGMArmorPenetration = 800;
            heli.AGMSpeed = 240;
            heli.AGMRange = 4000;
            heli.ASMCount = 0;
            heli.ASMArmorPenetration = 0;
            heli.ASMSpeed = 0;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon32601);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon32601);
            heli.HandingAGM = true;
            heli.HandingASM = false;
            heli.HandingCannon = false;
            heli.HandingBomb = false;
            heli.Flares = true;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 32603;
            heli.Image = Resource.Drawable.img32603;
            heli.FlagImage = Resource.Drawable._flagFRG;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestFRG;
            heli.Name = "BO 105 PAH-1A1";
            heli.Nation = context.Resources.GetString(Resource.String.NationGermany);
            heli.NationId = 2;
            heli.Rank = "VI";
            heli.RankId = 6;
            heli.BR = 9.7;
            heli.Type = context.Resources.GetString(Resource.String.UtilityHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.83;
            heli.FirstFlyYear = 1967;
            heli.MaxSpeed = 261;
            heli.ClimbTo1000 = 118;
            heli.Turn360 = 8;
            heli.EnginePower = 880;
            heli.Weight = 2500;
            heli.ThrustToWeightRatio = 0.35;
            heli.AGMCount = 6;
            heli.AGMArmorPenetration = 900;
            heli.AGMSpeed = 240;
            heli.AGMRange = 4000;
            heli.ASMCount = 0;
            heli.ASMArmorPenetration = 0;
            heli.ASMSpeed = 0;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon32603);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon32603);
            heli.HandingAGM = true;
            heli.HandingASM = false;
            heli.HandingCannon = false;
            heli.HandingBomb = false;
            heli.Flares = true;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 32602;
            heli.Image = Resource.Drawable.img32602;
            heli.FlagImage = Resource.Drawable._flagGDR;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestGDR;
            heli.Name = "Mi-24P";
            heli.Nation = context.Resources.GetString(Resource.String.NationGermany);
            heli.NationId = 2;
            heli.Rank = "VI";
            heli.RankId = 6;
            heli.BR = 9.7;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.83;
            heli.FirstFlyYear = 1974;
            heli.MaxSpeed = 360;
            heli.ClimbTo1000 = 69;
            heli.Turn360 = 8;
            heli.EnginePower = 4200;
            heli.Weight = 11500;
            heli.ThrustToWeightRatio = 0.37;
            heli.AGMCount = 4;
            heli.AGMArmorPenetration = 650;
            heli.AGMSpeed = 400;
            heli.AGMRange = 5000;
            heli.ASMCount = 80;
            heli.ASMArmorPenetration = 400;
            heli.ASMSpeed = 610;
            heli.BombLoad = 1000;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon32602);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon32602);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = true;
            heli.AirToAir = true;
            heli.Flares = true;
            heli.IRCM = true;
            heli.HIRSS = true;
            heli.AirToAir = true;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 32604;
            heli.Image = Resource.Drawable.img32604;
            heli.FlagImage = Resource.Drawable._flagGDR;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestGDR;
            heli.Name = "◊ Mi-24P HFS 80";
            heli.Nation = context.Resources.GetString(Resource.String.NationGermany);
            heli.NationId = 2;
            heli.Rank = "VI";
            heli.RankId = 6;
            heli.BR = 9.7;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypePremium);
            heli.PatchAdded = 1.91;
            heli.FirstFlyYear = 1972;
            heli.MaxSpeed = 360;
            heli.ClimbTo1000 = 103;
            heli.Turn360 = 7;
            heli.EnginePower = 4200;
            heli.Weight = 11500;
            heli.ThrustToWeightRatio = 0.37;
            heli.AGMCount = 4;
            heli.AGMArmorPenetration = 560;
            heli.AGMSpeed = 400;
            heli.AGMRange = 5000;
            heli.ASMCount = 80;
            heli.ASMArmorPenetration = 400;
            heli.ASMSpeed = 610;
            heli.BombLoad = 1126;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon32604);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon32604);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = true;
            heli.AirToAir = true;
            heli.Flares = true;
            heli.IRCM = true;
            heli.HIRSS = true;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 32701;
            heli.Image = Resource.Drawable.img32701;
            heli.FlagImage = Resource.Drawable._flagFRG;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestFRG;
            heli.Name = "EC-665 Tiger UHT";
            heli.Nation = context.Resources.GetString(Resource.String.NationGermany);
            heli.NationId = 2;
            heli.Rank = "VII";
            heli.RankId = 7;
            heli.BR = 10.3;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.91;
            heli.FirstFlyYear = 1991;
            heli.MaxSpeed = 290;
            heli.ClimbTo1000 = 82;
            heli.Turn360 = 7;
            heli.EnginePower = 2570;
            heli.Weight = 6000;
            heli.ThrustToWeightRatio = 0.43;
            heli.AGMCount = 8;
            heli.AGMArmorPenetration = 1000;
            heli.AGMSpeed = 290;
            heli.AGMRange = 7000;
            heli.ASMCount = 76;
            heli.ASMArmorPenetration = 290;
            heli.ASMSpeed = 739;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon32701);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon32701);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.AirToAir = true;
            heli.HandingBomb = false;
            heli.Flares = true;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 33604;
            heli.Image = Resource.Drawable.img33604;
            heli.FlagImage = Resource.Drawable._flagRussia;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestRussia;
            heli.Name = "◊ Ka-50";
            heli.Nation = context.Resources.GetString(Resource.String.NationUSSR);
            heli.NationId = 3;
            heli.Rank = "VI";
            heli.RankId = 6;
            heli.BR = 10.0;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypePremium);
            heli.PatchAdded = 1.93;
            heli.FirstFlyYear = 1982;
            heli.MaxSpeed = 332;
            heli.ClimbTo1000 = 72;
            heli.Turn360 = 7;
            heli.EnginePower = 4574;
            heli.Weight = 10800;
            heli.ThrustToWeightRatio = 0.42;
            heli.AGMCount = 12;
            heli.AGMArmorPenetration = 1000;
            heli.AGMSpeed = 600;
            heli.AGMRange = 10000;
            heli.ASMCount = 80;
            heli.ASMArmorPenetration = 400;
            heli.ASMSpeed = 610;
            heli.BombLoad = 956;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon33604);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon33604);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = true;
            heli.AirToAir = true;
            heli.Flares = true;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 33701;
            heli.Image = Resource.Drawable.img33701;
            heli.FlagImage = Resource.Drawable._flagRussia;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestRussia;
            heli.Name = "Mi-28N";
            heli.Nation = context.Resources.GetString(Resource.String.NationUSSR);
            heli.NationId = 3;
            heli.Rank = "VI";
            heli.RankId = 6;
            heli.BR = 10.3;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.93;
            heli.FirstFlyYear = 1996;
            heli.MaxSpeed = 330;
            heli.ClimbTo1000 = 112;
            heli.Turn360 = 8;
            heli.EnginePower = 4400;
            heli.Weight = 11500;
            heli.ThrustToWeightRatio = 0.38;
            heli.AGMCount = 8;
            heli.AGMArmorPenetration = 950;
            heli.AGMSpeed = 550;
            heli.AGMRange = 8000;
            heli.ASMCount = 80;
            heli.ASMArmorPenetration = 400;
            heli.ASMSpeed = 610;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon33701);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon33701);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = false;
            heli.AirToAir = true;
            heli.Flares = true;
            helis.Add(heli);


            ///////////////////////////////////////////   СССР   ///////////////////////////////////////////


            heli = new Heli();
            heli.Id = 33501;
            heli.Image = Resource.Drawable.img33501;
            heli.FlagImage = Resource.Drawable._flagUSSR;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestUSSR;
            heli.Name = context.Resources.GetString(Resource.String.Name33501);
            heli.Nation = context.Resources.GetString(Resource.String.NationUSSR);
            heli.NationId = 3;
            heli.Rank = "V";
            heli.RankId = 5;
            heli.BR = 8.3;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.81;
            heli.FirstFlyYear = 1952;
            heli.MaxSpeed = 275;
            heli.ClimbTo1000 = 100;
            heli.Turn360 = 8;
            heli.EnginePower = 1700;
            heli.Weight = 7600;
            heli.ThrustToWeightRatio = 0.22;
            heli.AGMCount = 4;
            heli.AGMArmorPenetration = 650;
            heli.AGMSpeed = 220;
            heli.AGMRange = 4000;
            heli.ASMCount = 96;
            heli.ASMArmorPenetration = 150;
            heli.ASMSpeed = 610;
            heli.BombLoad = 900;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon33501);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon33501);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = false;
            heli.HandingBomb = true;
            helis.Add(heli);



            heli = new Heli();
            heli.Id = 33502;
            heli.Image = Resource.Drawable.img33502;
            heli.FlagImage = Resource.Drawable._flagUSSR;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestUSSR;
            heli.Name = context.Resources.GetString(Resource.String.Name33502);
            heli.Nation = context.Resources.GetString(Resource.String.NationUSSR);
            heli.NationId = 3;
            heli.Rank = "V";
            heli.RankId = 5;
            heli.BR = 9.0;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.81;
            heli.FirstFlyYear = 1969;
            heli.MaxSpeed = 360;
            heli.ClimbTo1000 = 69;
            heli.Turn360 = 8;
            heli.EnginePower = 4200;
            heli.Weight = 11500;
            heli.ThrustToWeightRatio = 0.37;
            heli.AGMCount = 4;
            heli.AGMArmorPenetration = 650;
            heli.AGMSpeed = 220;
            heli.AGMRange = 4000;
            heli.ASMCount = 128;
            heli.ASMArmorPenetration = 150;
            heli.ASMSpeed = 610;
            heli.BombLoad = 1000;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon33502);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon33502);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = false;
            heli.HandingBomb = true;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 33503;
            heli.Image = Resource.Drawable.img33503;
            heli.FlagImage = Resource.Drawable._flagCzech;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestCzech;
            heli.Name = context.Resources.GetString(Resource.String.Name33503);
            heli.Nation = context.Resources.GetString(Resource.String.NationUSSR);
            heli.NationId = 3;
            heli.Rank = "V";
            heli.RankId = 5;
            heli.BR = 9.3;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypePremium);
            heli.PatchAdded = 1.81;
            heli.FirstFlyYear = 1972;
            heli.MaxSpeed = 360;
            heli.ClimbTo1000 = 69;
            heli.Turn360 = 8;
            heli.EnginePower = 4200;
            heli.Weight = 11500;
            heli.ThrustToWeightRatio = 0.37;
            heli.AGMCount = 4;
            heli.AGMArmorPenetration = 650;
            heli.AGMSpeed = 230;
            heli.AGMRange = 4000;
            heli.ASMCount = 128;
            heli.ASMArmorPenetration = 150;
            heli.ASMSpeed = 610;
            heli.BombLoad = 1000;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon33503);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon33503);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = true;
            heli.IRCM = true;
            heli.Flares = true;
            helis.Add(heli);

            heli = new Heli();
            heli.Id = 33601;
            heli.Image = Resource.Drawable.img33601;
            heli.FlagImage = Resource.Drawable._flagUSSR;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestUSSR;
            heli.Name = context.Resources.GetString(Resource.String.Name33601);
            heli.Nation = context.Resources.GetString(Resource.String.NationUSSR);
            heli.NationId = 3;
            heli.Rank = "VI";
            heli.RankId = 6;
            heli.BR = 9.7;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.81;
            heli.FirstFlyYear = 1972;
            heli.MaxSpeed = 360;
            heli.ClimbTo1000 = 69;
            heli.Turn360 = 8;
            heli.EnginePower = 4200;
            heli.Weight = 11500;
            heli.ThrustToWeightRatio = 0.37;
            heli.AGMCount = 8;
            heli.AGMArmorPenetration = 560;
            heli.AGMSpeed = 400;
            heli.AGMRange = 5000;
            heli.ASMCount = 80;
            heli.ASMArmorPenetration = 400;
            heli.ASMSpeed = 610;
            heli.BombLoad = 1000;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon33601);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon33601);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = true;
            heli.IRCM = true;
            heli.HIRSS = true;
            heli.Flares = true;
            heli.AirToAir = true;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 33602;
            heli.Image = Resource.Drawable.img33602;
            heli.FlagImage = Resource.Drawable._flagUSSR;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestUSSR;
            heli.Name = context.Resources.GetString(Resource.String.Name33602);
            heli.Nation = context.Resources.GetString(Resource.String.NationUSSR);
            heli.NationId = 3;
            heli.Rank = "VI";
            heli.RankId = 6;
            heli.BR = 9.7;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.81;
            heli.FirstFlyYear = 1974;
            heli.MaxSpeed = 360;
            heli.ClimbTo1000 = 69;
            heli.Turn360 = 8;
            heli.EnginePower = 4200;
            heli.Weight = 11500;
            heli.ThrustToWeightRatio = 0.37;
            heli.AGMCount = 8;
            heli.AGMArmorPenetration = 560;
            heli.AGMSpeed = 400;
            heli.AGMRange = 5000;
            heli.ASMCount = 80;
            heli.ASMArmorPenetration = 400;
            heli.ASMSpeed = 610;
            heli.BombLoad = 1000;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon33602);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon33602);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = true;
            heli.IRCM = true;
            heli.HIRSS = true;
            heli.Flares = true;
            heli.AirToAir = true;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 33603;
            heli.Image = Resource.Drawable.img33603;
            heli.FlagImage = Resource.Drawable._flagRussia;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestRussia;
            heli.Name = context.Resources.GetString(Resource.String.Name33603);
            heli.Nation = context.Resources.GetString(Resource.String.NationUSSR);
            heli.NationId = 3;
            heli.Rank = "VI";
            heli.RankId = 6;
            heli.BR = 10.0;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.81;
            heli.FirstFlyYear = 1998;
            heli.MaxSpeed = 339;
            heli.ClimbTo1000 = 69;
            heli.Turn360 = 7;
            heli.EnginePower = 4400;
            heli.Weight = 11500;
            heli.ThrustToWeightRatio = 0.38;
            heli.AGMCount = 8;
            heli.AGMArmorPenetration = 800;
            heli.AGMSpeed = 550;
            heli.AGMRange = 6000;
            heli.ASMCount = 80;
            heli.ASMArmorPenetration = 400;
            heli.ASMSpeed = 610;
            heli.BombLoad = 1000;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon33603);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon33603);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = true;
            heli.AirToAir = true;
            heli.IRCM = true;
            heli.HIRSS = true;
            heli.Flares = true;
            helis.Add(heli);


            ///////////////////////////////////////////   БРИТАНІЯ   ///////////////////////////////////////////


            heli = new Heli();
            heli.Id = 34501;
            heli.Image = Resource.Drawable.img34501;
            heli.FlagImage = Resource.Drawable._flagBritain;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestBritain;
            heli.Name = "Scout AH.Mk.1";
            heli.Nation = context.Resources.GetString(Resource.String.NationGB);
            heli.NationId = 4;
            heli.Rank = "V";
            heli.RankId = 5;
            heli.BR = 8.7;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.91;
            heli.FirstFlyYear = 1960;
            heli.MaxSpeed = 217;
            heli.ClimbTo1000 = 155;
            heli.Turn360 = 6;
            heli.EnginePower = 685;
            heli.Weight = 2500;
            heli.ThrustToWeightRatio = 0.27;
            heli.AGMCount = 4;
            heli.AGMArmorPenetration = 600;
            heli.AGMSpeed = 190;
            heli.AGMRange = 3000;
            heli.ASMCount = 0;
            heli.ASMArmorPenetration = 0;
            heli.ASMSpeed = 0;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon34501);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon34501);
            heli.HandingAGM = true;
            heli.HandingASM = false;
            heli.HandingCannon = false;
            heli.HandingBomb = false;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 34502;
            heli.Image = Resource.Drawable.img34502;
            heli.FlagImage = Resource.Drawable._flagBritain;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestBritain;
            heli.Name = "Wasp HAS.Mk.1";
            heli.Nation = context.Resources.GetString(Resource.String.NationGB);
            heli.NationId = 4;
            heli.Rank = "V";
            heli.RankId = 5;
            heli.BR = 8.7;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.91;
            heli.FirstFlyYear = 1962;
            heli.MaxSpeed = 223;
            heli.ClimbTo1000 = 167;
            heli.Turn360 = 6;
            heli.EnginePower = 710;
            heli.Weight = 2500;
            heli.ThrustToWeightRatio = 0.28;
            heli.AGMCount = 4;
            heli.AGMArmorPenetration = 600;
            heli.AGMSpeed = 190;
            heli.AGMRange = 3000;
            heli.ASMCount = 0;
            heli.ASMArmorPenetration = 0;
            heli.ASMSpeed = 0;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon34502);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon34502);
            heli.HandingAGM = true;
            heli.HandingASM = false;
            heli.HandingCannon = false;
            heli.HandingBomb = false;
            helis.Add(heli);

            heli = new Heli();
            heli.Id = 34601;
            heli.Image = Resource.Drawable.img34601;
            heli.FlagImage = Resource.Drawable._flagBritain;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestBritain;
            heli.Name = "Lynx AH.Mk.1";
            heli.Nation = context.Resources.GetString(Resource.String.NationGB);
            heli.NationId = 4;
            heli.Rank = "VI";
            heli.RankId = 6;
            heli.BR = 9.7;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.91;
            heli.FirstFlyYear = 1971;
            heli.MaxSpeed = 288;
            heli.ClimbTo1000 = 94;
            heli.Turn360 = 7;
            heli.EnginePower = 1680;
            heli.Weight = 4500;
            heli.ThrustToWeightRatio = 0.37;
            heli.AGMCount = 8;
            heli.AGMArmorPenetration = 1100;
            heli.AGMSpeed = 475;
            heli.AGMRange = 8000;
            heli.ASMCount = 38;
            heli.ASMArmorPenetration = 290;
            heli.ASMSpeed = 739;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon34601);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon34601);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = false;
            heli.AirToAir = true;
            heli.Flares = true;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 34602;
            heli.Image = Resource.Drawable.img34602;
            heli.FlagImage = Resource.Drawable._flagBritain;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestBritain;
            heli.Name = "◊ G-LYNX";
            heli.Nation = context.Resources.GetString(Resource.String.NationGB);
            heli.NationId = 4;
            heli.Rank = "VI";
            heli.RankId = 6;
            heli.BR = 9.7;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypePremium);
            heli.PatchAdded = 1.91;
            heli.FirstFlyYear = 1971;
            heli.MaxSpeed = 340;
            heli.ClimbTo1000 = 81;
            heli.Turn360 = 7;
            heli.EnginePower = 2464;
            heli.Weight = 5900;
            heli.ThrustToWeightRatio = 0.40;
            heli.AGMCount = 8;
            heli.AGMArmorPenetration = 1100;
            heli.AGMSpeed = 475;
            heli.AGMRange = 8000;
            heli.ASMCount = 38;
            heli.ASMArmorPenetration = 290;
            heli.ASMSpeed = 739;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon34602);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon34602);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = false;
            heli.AirToAir = true;
            heli.Flares = true;
            helis.Add(heli);


            ///////////////////////////////////////////   ІТАЛІЯ   ///////////////////////////////////////////


            heli = new Heli();
            heli.Id = 36601;
            heli.Image = Resource.Drawable.img36601;
            heli.FlagImage = Resource.Drawable._flagItalyNew;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestItalyNew;
            heli.Name = "◊ A-129 International";
            heli.Nation = context.Resources.GetString(Resource.String.NationItaly);
            heli.NationId = 6;
            heli.Rank = "VI";
            heli.RankId = 6;
            heli.BR = 9.7;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypePremium);
            heli.PatchAdded = 1.93;
            heli.FirstFlyYear = 1983;
            heli.MaxSpeed = 309;
            heli.ClimbTo1000 = 128;
            heli.Turn360 = 8;
            heli.EnginePower = 2720;
            heli.Weight = 5100;
            heli.ThrustToWeightRatio = 0.53;
            heli.AGMCount = 8;
            heli.AGMArmorPenetration = 1100;
            heli.AGMSpeed = 475;
            heli.AGMRange = 8000;
            heli.ASMCount = 38;
            heli.ASMArmorPenetration = 290;
            heli.ASMSpeed = 739;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon36601);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon36601);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = false;
            heli.AirToAir = false;
            heli.Flares = false;
            helis.Add(heli);



            ///////////////////////////////////////////   ЯПОНІЯ   ///////////////////////////////////////////

            heli = new Heli();
            heli.Id = 35501;
            heli.Image = Resource.Drawable.img35501;
            heli.FlagImage = Resource.Drawable._flagJapanNew;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestJapanNew;
            heli.Name = "◊ AH-1S Kisarazu";
            heli.Nation = context.Resources.GetString(Resource.String.NationJapan);
            heli.NationId = 5;
            heli.Rank = "V";
            heli.RankId = 5;
            heli.BR = 9.7;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypePremium);
            heli.PatchAdded = 1.89;
            heli.FirstFlyYear = 1965;
            heli.MaxSpeed = 274;
            heli.ClimbTo1000 = 90;
            heli.Turn360 = 7;
            heli.EnginePower = 1300;
            heli.Weight = 4500;
            heli.ThrustToWeightRatio = 0.29;
            heli.AGMCount = 8;
            heli.AGMArmorPenetration = 630;
            heli.AGMSpeed = 296;
            heli.AGMRange = 3000;
            heli.ASMCount = 76;
            heli.ASMArmorPenetration = 290;
            heli.ASMSpeed = 739;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon35501);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon35501);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = false;
            helis.Add(heli);


            ///////////////////////////////////////////   ФРАНЦІЯ   ///////////////////////////////////////////


            heli = new Heli();
            heli.Id = 37501;
            heli.Image = Resource.Drawable.img37501;
            heli.FlagImage = Resource.Drawable._flagFrance;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestFrance;
            heli.Name = "H-34";
            heli.Nation = context.Resources.GetString(Resource.String.NationFrance);
            heli.NationId = 7;
            heli.Rank = "V";
            heli.RankId = 5;
            heli.BR = 8.3;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.87;
            heli.FirstFlyYear = 1954;
            heli.MaxSpeed = 279;
            heli.ClimbTo1000 = 150;
            heli.Turn360 = 7;
            heli.EnginePower = 1420;
            heli.Weight = 6000;
            heli.ThrustToWeightRatio = 0.24;
            heli.AGMCount = 2;
            heli.AGMArmorPenetration = 600;
            heli.AGMSpeed = 190;
            heli.AGMRange = 3000;
            heli.ASMCount = 6;
            heli.ASMArmorPenetration = 36;
            heli.ASMSpeed = 420;
            heli.BombLoad = 879;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon37501);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon37501);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = false;
            heli.HandingBomb = true;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 37502;
            heli.Image = Resource.Drawable.img37502;
            heli.FlagImage = Resource.Drawable._flagFrance;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestFrance;
            heli.Name = "SA.313B Alouette II";
            heli.Nation = context.Resources.GetString(Resource.String.NationFrance);
            heli.NationId = 7;
            heli.Rank = "V";
            heli.RankId = 5;
            heli.BR = 8.7;
            heli.Type = context.Resources.GetString(Resource.String.UtilityHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.87;
            heli.FirstFlyYear = 1952;
            heli.MaxSpeed = 208;
            heli.ClimbTo1000 = 98;
            heli.Turn360 = 7;
            heli.EnginePower = 380;
            heli.Weight = 1600;
            heli.ThrustToWeightRatio = 0.24;
            heli.AGMCount = 4;
            heli.AGMArmorPenetration = 600;
            heli.AGMSpeed = 190;
            heli.AGMRange = 3000;
            heli.ASMCount = 72;
            heli.ASMArmorPenetration = 10;
            heli.ASMSpeed = 500;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon37502);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon37502);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = false;
            heli.HandingBomb = false;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 37503;
            heli.Image = Resource.Drawable.img37503;
            heli.FlagImage = Resource.Drawable._flagFrance;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestFrance;
            heli.Name = "SA.316B Alouette III";
            heli.Nation = context.Resources.GetString(Resource.String.NationFrance);
            heli.NationId = 7;
            heli.Rank = "V";
            heli.RankId = 5;
            heli.BR = 9.0;
            heli.Type = context.Resources.GetString(Resource.String.UtilityHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.87;
            heli.FirstFlyYear = 1959;
            heli.MaxSpeed = 240;
            heli.ClimbTo1000 = 81;
            heli.Turn360 = 7;
            heli.EnginePower = 570;
            heli.Weight = 1600;
            heli.ThrustToWeightRatio = 0.36;
            heli.AGMCount = 4;
            heli.AGMArmorPenetration = 600;
            heli.AGMSpeed = 190;
            heli.AGMRange = 3000;
            heli.ASMCount = 0;
            heli.ASMArmorPenetration = 0;
            heli.ASMSpeed = 0;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon37503);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon37503);
            heli.HandingAGM = true;
            heli.HandingASM = false;
            heli.HandingCannon = false;
            heli.HandingBomb = false;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 37504;
            heli.Image = Resource.Drawable.img37504;
            heli.FlagImage = Resource.Drawable._flagRomania;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestRomania;
            heli.Name = "◊ IAR 316B";
            heli.Nation = context.Resources.GetString(Resource.String.NationFrance);
            heli.NationId = 7;
            heli.Rank = "V";
            heli.RankId = 5;
            heli.BR = 9.3;
            heli.Type = context.Resources.GetString(Resource.String.UtilityHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypePremium);
            heli.PatchAdded = 1.87;
            heli.FirstFlyYear = 1971;
            heli.MaxSpeed = 240;
            heli.ClimbTo1000 = 81;
            heli.Turn360 = 7;
            heli.EnginePower = 570;
            heli.Weight = 1600;
            heli.ThrustToWeightRatio = 0.36;
            heli.AGMCount = 6;
            heli.AGMArmorPenetration = 800;
            heli.AGMSpeed = 220;
            heli.AGMRange = 3000;
            heli.ASMCount = 32;
            heli.ASMArmorPenetration = 150;
            heli.ASMSpeed = 810;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon37504);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon37504);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = false;
            heli.HandingBomb = false;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 37601;
            heli.Image = Resource.Drawable.img37601;
            heli.FlagImage = Resource.Drawable._flagFrance;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestFrance;
            heli.Name = "SA.341F Gazelle";
            heli.Nation = context.Resources.GetString(Resource.String.NationFrance);
            heli.NationId = 7;
            heli.Rank = "VI";
            heli.RankId = 6;
            heli.BR = 9.7;
            heli.Type = context.Resources.GetString(Resource.String.UtilityHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.87;
            heli.FirstFlyYear = 1967;
            heli.MaxSpeed = 278;
            heli.ClimbTo1000 = 140;
            heli.Turn360 = 7;
            heli.EnginePower = 500;
            heli.Weight = 2000;
            heli.ThrustToWeightRatio = 0.25;
            heli.AGMCount = 2;
            heli.AGMArmorPenetration = 900;
            heli.AGMSpeed = 240;
            heli.AGMRange = 4000;
            heli.ASMCount = 7;
            heli.ASMArmorPenetration = 290;
            heli.ASMSpeed = 739;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon37601);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon37601);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.AirToAir = true;
            heli.Flares = true;
            heli.HandingCannon = false;
            heli.HandingBomb = false;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 37602;
            heli.Image = Resource.Drawable.img37602;
            heli.FlagImage = Resource.Drawable._flagFrance;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestFrance;
            heli.Name = "SA.342M Gazelle";
            heli.Nation = context.Resources.GetString(Resource.String.NationFrance);
            heli.NationId = 7;
            heli.Rank = "VI";
            heli.RankId = 6;
            heli.BR = 9.7;
            heli.Type = context.Resources.GetString(Resource.String.UtilityHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.87;
            heli.FirstFlyYear = 1967;
            heli.MaxSpeed = 307;
            heli.ClimbTo1000 = 140;
            heli.Turn360 = 7;
            heli.EnginePower = 570;
            heli.Weight = 2000;
            heli.ThrustToWeightRatio = 0.29;
            heli.AGMCount = 4;
            heli.AGMArmorPenetration = 900;
            heli.AGMSpeed = 240;
            heli.AGMRange = 4000;
            heli.ASMCount = 14;
            heli.ASMArmorPenetration = 290;
            heli.ASMSpeed = 739;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon37602);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon37602);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.Flares = true;
            heli.AirToAir = true;
            heli.HandingCannon = false;
            heli.HandingBomb = false;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 37603;
            heli.Image = Resource.Drawable.img37603;
            heli.FlagImage = Resource.Drawable._flagFrance;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestFrance;
            heli.Name = "◊ EC-665 Tiger HAP";
            heli.Nation = context.Resources.GetString(Resource.String.NationFrance);
            heli.NationId = 7;
            heli.Rank = "VI";
            heli.RankId = 6;
            heli.BR = 10.0;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypePremium);
            heli.PatchAdded = 1.91;
            heli.FirstFlyYear = 1991;
            heli.MaxSpeed = 320;
            heli.ClimbTo1000 = 91;
            heli.Turn360 = 7;
            heli.EnginePower = 2570;
            heli.Weight = 6000;
            heli.ThrustToWeightRatio = 0.43;
            heli.AGMCount = 8;
            heli.AGMArmorPenetration = 1250;
            heli.AGMSpeed = 240;
            heli.AGMRange = 4300;
            heli.ASMCount = 68;
            heli.ASMArmorPenetration = 300;
            heli.ASMSpeed = 600;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon37603);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon37603);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.HandingCannon = true;
            heli.HandingBomb = false;
            heli.AirToAir = true;
            heli.Flares = true;
            helis.Add(heli);


            heli = new Heli();
            heli.Id = 37701;
            heli.Image = Resource.Drawable.img37701;
            heli.FlagImage = Resource.Drawable._flagFrance;
            heli.FlagImageTheBest = Resource.Drawable._flagTheBestFrance;
            heli.Name = "EC-665 Tiger HAD";
            heli.Nation = context.Resources.GetString(Resource.String.NationFrance);
            heli.NationId = 7;
            heli.Rank = "VII";
            heli.RankId = 7;
            heli.BR = 10.3;
            heli.Type = context.Resources.GetString(Resource.String.AttackHelicopter);
            heli.HeliCharacter = context.Resources.GetString(Resource.String.TypeOrdinary);
            heli.PatchAdded = 1.91;
            heli.FirstFlyYear = 1991;
            heli.MaxSpeed = 331;
            heli.ClimbTo1000 = 93;
            heli.Turn360 = 7;
            heli.EnginePower = 2934;
            heli.Weight = 6000;
            heli.ThrustToWeightRatio = 0.49;
            heli.AGMCount = 8;
            heli.AGMArmorPenetration = 1100;
            heli.AGMSpeed = 475;
            heli.AGMRange = 8000;
            heli.ASMCount = 68;
            heli.ASMArmorPenetration = 300;
            heli.ASMSpeed = 600;
            heli.BombLoad = 0;
            heli.OffensiveWeapon = context.Resources.GetString(Resource.String.HeliOffensiveWeapon37701);
            heli.SuspensionWeapon = context.Resources.GetString(Resource.String.SuspensionWeapon37701);
            heli.HandingAGM = true;
            heli.HandingASM = true;
            heli.AirToAir = true;
            heli.HandingCannon = true;
            heli.HandingBomb = false;
            heli.Flares = true;
            helis.Add(heli);




            return helis;
        }



    }
}